<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="0" passed="0">
  <reporter-output>
    <line>
      <![CDATA[About to begin executing Test Sample Test]]>
    </line>
    <line>
      <![CDATA[About to end executing Test Sample Test]]>
    </line>
  </reporter-output>
  <suite name="Sample Suite" duration-ms="37" started-at="2018-12-15T09:24:03Z" finished-at="2018-12-15T09:24:03Z">
    <groups>
    </groups>
    <test name="Sample Test" duration-ms="37" started-at="2018-12-15T09:24:03Z" finished-at="2018-12-15T09:24:03Z">
      <class name="util.ExecuteTestCases">
        <test-method status="FAIL" signature="setup()[pri:0, instance:util.ExecuteTestCases@32d992b2]" test-instance-name="" name="setup" is-config="true" duration-ms="0" started-at="2018-12-15T14:54:03Z" finished-at="2018-12-15T14:54:03Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at util.ExcelLibrary.getNumberOfSheetsinSuite(ExcelLibrary.java:77)
	at util.ExcelAction.readTestSuite(ExcelAction.java:226)
	at util.ExecuteTestCases.setup(ExecuteTestCases.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:175)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:107)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at util.MainTestNG.testng(MainTestNG.java:119)
	at util.MainTestNG.main(MainTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="SKIP" signature="cleanup()[pri:0, instance:util.ExecuteTestCases@32d992b2]" test-instance-name="" name="cleanup" is-config="true" duration-ms="0" started-at="2018-12-15T14:54:03Z" finished-at="2018-12-15T14:54:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanup -->
      </class> <!-- util.ExecuteTestCases -->
    </test> <!-- Sample Test -->
  </suite> <!-- Sample Suite -->
</testng-results>
